name: Build and Push Frontend to Docker Hub

on:
  push:
    branches:
      - main
      - feature/workflow
      - fix/ip

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build and push
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build an push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/FrontEnd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/FrontEnd:v${{ github.run_number }}